version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 10s
  web:
    image: grocerypsql:v1
    ports:
      - "5000:5000"
    environment:
      - url=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
        restart: true
    links:
      - db
    