version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdata
  web:
    image: grocerypsql:v1
    ports:
      - "5000:5000"
    environment:
      - url=postgresdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db